# this is to proxy API requests to the backend using netlify.  Http proxy middleware was not working

[[redirects]]
  from = "/api/*"
  to = "https://habit-tracker-4.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "https://habit-tracker-4.herokuapp.com/auth/:splat"
  status = 200